/**
 * MiniCut Indonesian-only UI translation bridge.
 *
 * OpenChatCut uses Chinese source strings as i18n keys. MiniCut never renders
 * those keys directly. We resolve through the upstream English dictionary and
 * then convert supported UI copy to Indonesian. Unknown non-technical copy is
 * replaced with a safe Indonesian placeholder instead of leaking another
 * language into the interface.
 */

const DIRECT: Record<string, string> = {
  // Top bar / common actions
  'Switch UI language': 'Bahasa antarmuka',
  'Back to projects': 'Kembali ke proyek',
  'Double-click to rename': 'Klik dua kali untuk mengganti nama',
  'Edit keyboard shortcuts': 'Edit pintasan keyboard',
  'Undo': 'Urungkan',
  'Redo': 'Ulangi',
  'Design style (brand)': 'Gaya desain (merek)',
  'Version History': 'Riwayat versi',
  'Toggle panel layout': 'Ubah tata letak panel',
  'Export MP4': 'Ekspor MP4',
  'Exporting…': 'Mengekspor…',
  'Export': 'Ekspor',
  'Account': 'Akun',
  'Window controls': 'Kontrol jendela',
  'Close window': 'Tutup jendela',
  'Minimize window': 'Minimalkan jendela',
  'Zoom window': 'Perbesar jendela',
  'Settings': 'Pengaturan',
  'Close': 'Tutup',
  'Cancel': 'Batal',
  'Save': 'Simpan',
  'Open': 'Buka',
  'Delete': 'Hapus',
  'Remove': 'Hapus',
  'Add': 'Tambah',
  'Edit': 'Edit',
  'Copy': 'Salin',
  'Paste': 'Tempel',
  'Cut': 'Potong',
  'Search': 'Cari',
  'Reset': 'Atur ulang',
  'Retry': 'Coba lagi',
  'Continue': 'Lanjutkan',
  'Confirm': 'Konfirmasi',
  'Apply': 'Terapkan',
  'Done': 'Selesai',
  'Loading…': 'Memuat…',
  'Processing…': 'Memproses…',
  'Project': 'Proyek',
  'Projects': 'Proyek',
  'New project': 'Proyek baru',
  'Media': 'Media',
  'Timeline': 'Linimasa',
  'Transcript': 'Transkrip',
  'Captions': 'Takarir',
  'Subtitle': 'Subtitel',
  'Subtitles': 'Subtitel',
  'Audio': 'Audio',
  'Video': 'Video',
  'Image': 'Gambar',
  'Images': 'Gambar',
  'Text': 'Teks',
  'Effects': 'Efek',
  'Transitions': 'Transisi',
  'Speed': 'Kecepatan',
  'Volume': 'Volume',
  'Opacity': 'Opasitas',
  'Position': 'Posisi',
  'Rotation': 'Rotasi',
  'Scale': 'Skala',
  'Duration': 'Durasi',
  'Start': 'Mulai',
  'End': 'Akhir',
  'Name': 'Nama',
  'Type': 'Jenis',
  'Status': 'Status',
  'Error': 'Kesalahan',
  'Warning': 'Peringatan',
  'Success': 'Berhasil',
  'Failed': 'Gagal',
  'Ready': 'Siap',
  'Enabled': 'Aktif',
  'Disabled': 'Nonaktif',
  'Auto': 'Otomatis',
  'Manual': 'Manual',
  'Default': 'Bawaan',
  'Advanced': 'Lanjutan',
  'General': 'Umum',
  'Language': 'Bahasa',
  'Model': 'Model',
  'Provider': 'Penyedia',
  'Agent': 'Agent',
  'AI Chat': 'Chat AI',
  'Reasoning': 'Penalaran',
  'API Key': 'API Key',
  'Base URL': 'Base URL',
  'Export directory': 'Folder ekspor',
  'Select export directory': 'Pilih folder ekspor',
  'Select export file': 'Pilih file ekspor',
  'Select media save directory': 'Pilih folder penyimpanan media',
  'No clips were modified.': 'Tidak ada klip yang diubah.',
  'Voice isolation failed; no clips were modified.': 'Pemisahan suara gagal; tidak ada klip yang diubah.',
  'Loudness analysis failed; no clips were modified.': 'Analisis kenyaringan gagal; tidak ada klip yang diubah.',
  'Source media changed; the previous voice separation result was discarded. Retry.':
    'Media sumber berubah; hasil pemisahan suara sebelumnya dibuang. Coba lagi.',
  // Project / editor shell
  'Loading project…': 'Memuat proyek…',
  'Loading editor…': 'Memuat editor…',
  'Project not found, going back…': 'Proyek tidak ditemukan, kembali…',
  'Project data is temporarily unreadable': 'Data proyek sementara tidak dapat dibaca',
  'Project save failed. Retry before closing or switching projects.': 'Penyimpanan proyek gagal. Coba lagi sebelum menutup atau berpindah proyek.',
  'The project is still unsaved, so navigation was blocked. Keep editing to retry.': 'Proyek belum tersimpan, jadi perpindahan halaman diblokir. Lanjutkan mengedit untuk mencoba lagi.',
  'Just now': 'Baru saja',
  '{n} min ago': '{n} menit lalu',
  '{n} hr ago': '{n} jam lalu',
  '{n} d ago': '{n} hari lalu',
  'Generation Tasks': 'Tugas generasi',
  'Resume Tasks': 'Lanjutkan tugas',
  'Loading tasks…': 'Memuat tugas…',
  'No generation tasks': 'Tidak ada tugas generasi',
  'Pending': 'Menunggu',
  'Running': 'Berjalan',
  'Completed': 'Selesai',
  'Not Found': 'Tidak ditemukan',
  'Check Progress': 'Periksa progres',
  'Open Result': 'Buka hasil',
  'Retry Recoverable Tasks': 'Coba ulang tugas yang bisa dipulihkan',
  'Settings · API Keys': 'Pengaturan · API Key',
  'Configure a model to start using the Agent': 'Atur model untuk mulai menggunakan Agent',
  'Configure any cloud or local model to use conversational editing in the editor.': 'Atur model cloud atau lokal untuk memakai pengeditan percakapan di editor.',
  'Configure Model': 'Atur model',
  'Search projects': 'Cari proyek',
  'Clear search': 'Hapus pencarian',
  'No projects match “{query}”': 'Tidak ada proyek yang cocok dengan “{query}”',
  'New Project': 'Proyek baru',
  'Open {name}': 'Buka {name}',
  'Confirm Delete': 'Konfirmasi hapus',
  'Rename': 'Ganti nama',
  'Duplicate': 'Duplikat',
  'Import Project': 'Impor proyek',
  'Export History': 'Riwayat ekspor',
  'No exports yet': 'Belum ada ekspor',
  'Open Folder': 'Buka folder',
  'Clear History': 'Hapus riwayat',
  'No versions saved yet': 'Belum ada versi tersimpan',
  'Restore': 'Pulihkan',
  'Delete this version': 'Hapus versi ini',
  'Version name': 'Nama versi',
  'Save Current Version': 'Simpan versi saat ini',
  'Preview': 'Pratinjau',
  'Safe Area': 'Area aman',
  'Preview quality': 'Kualitas pratinjau',
  'High quality': 'Kualitas tinggi',
  'Smooth': 'Lancar',
  'Drop media here': 'Letakkan media di sini',
  'Previous keyframe': 'Keyframe sebelumnya',
  'Next keyframe': 'Keyframe berikutnya',
  'Add a keyframe at the playhead': 'Tambah keyframe di playhead',
  'Delete the keyframe at the playhead': 'Hapus keyframe di playhead',
  'Linear': 'Linear',
  'Ease In': 'Ease In',
  'Ease Out': 'Ease Out',
  'Ease In-Out': 'Ease In-Out',
  'Font Size': 'Ukuran font',
  'Color': 'Warna',
  'Align': 'Perataan',
  'Left': 'Kiri',
  'Center': 'Tengah',
  'Right': 'Kanan',
  'Weight': 'Ketebalan',
  'Regular': 'Normal',
  'Bold': 'Tebal',
  'Crop Left': 'Potong kiri',
  'Crop Right': 'Potong kanan',
  'Crop Top': 'Potong atas',
  'Crop Bottom': 'Potong bawah',
  'Fade In': 'Fade masuk',
  'Fade Out': 'Fade keluar',
  'Keyframes': 'Keyframe',
  'Brightness': 'Kecerahan',
  'Contrast': 'Kontras',
  'Saturation': 'Saturasi',
  'Blur': 'Blur',
  'Auto Color': 'Warna otomatis',

  // Agent / chat
  'Expand OpenChatCut Agent': 'Perluas Agent MiniCut',
  'Collapse OpenChatCut Agent': 'Ciutkan Agent MiniCut',
  'Clear chat': 'Hapus chat',
  'Agent workspace': 'Ruang kerja Agent',
  'Jump to top': 'Ke paling atas',
  'Jump to bottom': 'Ke paling bawah',
  'Start here': 'Mulai di sini',
  'Start with an editing goal': 'Mulai dengan tujuan pengeditan',
  'Choose a workflow, or describe the finished video you want.': 'Pilih alur kerja atau jelaskan hasil video yang kamu inginkan.',
  'Thinking…': 'Berpikir…',
  'Describe what you want to create...': 'Jelaskan apa yang ingin kamu buat...',
  'Tell the AI what to change — @ to reference assets': 'Beri tahu AI apa yang harus diubah — gunakan @ untuk merujuk aset',
  'Import failed': 'Impor gagal',
  'Agent change log': 'Riwayat perubahan Agent',
  'Resend': 'Kirim ulang',
  'Server-side': 'Sisi server',
  'Awaiting approval': 'Menunggu persetujuan',
  'Awaiting reply': 'Menunggu jawaban',
  'Cancelled': 'Dibatalkan',
  'Interrupted': 'Terputus',
  'Unknown status': 'Status tidak diketahui',
  'Context and tools': 'Konteks dan alat',
  'Input': 'Input',
  'Output': 'Output',
  'System': 'Sistem',
  'History': 'Riwayat',
  'Active tools': 'Alat aktif',
  'Tool schemas': 'Skema alat',
  'Model requests': 'Permintaan model',
  'Total input': 'Total input',
  'Total output': 'Total output',
  'Retries': 'Percobaan ulang',
  'Validation failed': 'Validasi gagal',
  'Denied': 'Ditolak',
  'Unknown tool': 'Alat tidak dikenal',
  'Approvals': 'Persetujuan',
  'Original operation': 'Operasi asli',
  'Operation ID': 'ID operasi',
  'Action': 'Aksi',
  'Command': 'Perintah',
  'File path': 'Path file',
  'Path': 'Path',
  'Repository': 'Repositori',
  'Install directory': 'Folder instalasi',
  'Skill': 'Skill',
  'Asset ID': 'ID aset',
  'Project ID': 'ID proyek',
  'Template ID': 'ID template',
  'Version ID': 'ID versi',
  'Prompt': 'Prompt',
  'Format': 'Format',
  'Codec': 'Codec',
  'Resolution': 'Resolusi',
  'Output directory': 'Folder output',
  'Quick actions': 'Aksi cepat',
  'Quick actions…': 'Aksi cepat…',
  'Remove filler words': 'Hapus kata pengisi',
  'Remove silence': 'Hapus bagian hening',
  'Jump cut': 'Jump cut',
  'Generate captions': 'Buat takarir',
  'Normalize loudness': 'Normalkan kenyaringan',
  'Landscape to portrait': 'Lanskap ke potret',
  'Clean talking-head edit': 'Rapikan video talking-head',
  'Remove pauses and filler, then sync captions': 'Hapus jeda dan kata pengisi, lalu sinkronkan takarir',
  'Motion package': 'Paket motion',
  'Titles, info cards, and transitions': 'Judul, kartu info, dan transisi',
  'Long-form highlights': 'Sorotan video panjang',
  'Find highlights and reshape them as shorts': 'Cari sorotan dan ubah menjadi video pendek',
  'Product story': 'Cerita produk',
  'AI visual': 'Visual AI',
  'Knowledge video': 'Video pengetahuan',

  // Media pool
  'Search media': 'Cari media',
  'Upload media': 'Unggah media',
  'Add solid color': 'Tambah warna solid',
  'New folder': 'Folder baru',
  'Sort media': 'Urutkan media',
  'Newest first': 'Terbaru dulu',
  'Name A–Z': 'Nama A–Z',
  'Filter media': 'Filter media',
  'All': 'Semua',
  'Document': 'Dokumen',
  'Other files': 'File lain',
  'Favorite': 'Favorit',
  'Relink Offline Media': 'Hubungkan ulang media offline',
  'Relink file': 'Hubungkan ulang file',
  'Back to parent folder': 'Kembali ke folder induk',
  'Rename folder': 'Ganti nama folder',
  'Delete empty folder': 'Hapus folder kosong',
  'Clear selection': 'Hapus pilihan',
  'Select all': 'Pilih semua',
  'Deselect all': 'Batalkan semua pilihan',
  'Selected {n}': '{n} dipilih',
  'Add to timeline': 'Tambahkan ke linimasa',
  'Download original': 'Unduh file asli',
  'Move selected assets': 'Pindahkan aset terpilih',
  'Move to…': 'Pindahkan ke…',
  'This folder is empty': 'Folder ini kosong',
  'Import media or drag files here.': 'Impor media atau seret file ke sini.',
  'Used on a timeline': 'Dipakai di linimasa',
  'Delete In-Use Media': 'Hapus media yang sedang dipakai',
  'Asset display name': 'Nama tampilan aset',
  'Batch rename media': 'Ganti nama media massal',
  'Copy selected': 'Salin yang dipilih',
  'Paste copies': 'Tempel salinan',
  'Paste media': 'Tempel media',
  'Convert': 'Konversi',
  'Clean Up Media': 'Bersihkan media',
  'Scanning… (collecting references per project)': 'Memindai… (mengumpulkan referensi tiap proyek)',
  'Deleting…': 'Menghapus…',
  'Delete selected': 'Hapus yang dipilih',
  'Uploading': 'Mengunggah',
  'Upload canceled': 'Unggahan dibatalkan',
  'File too large to upload': 'File terlalu besar untuk diunggah',
  'Upload from phone': 'Unggah dari ponsel',
  'Phone upload QR code': 'Kode QR unggahan ponsel',
  'Generating QR code…': 'Membuat kode QR…',
  'Local network address': 'Alamat jaringan lokal',
  'Copy link': 'Salin tautan',
  'Semantic search': 'Pencarian semantik',
  'Local semantic search': 'Pencarian semantik lokal',
  'Media never leaves this device': 'Media tidak pernah keluar dari perangkat ini',
  'Search by visual content': 'Cari berdasarkan isi visual',
  'Enable local model': 'Aktifkan model lokal',
  'Disable local model': 'Nonaktifkan model lokal',
  'GPU accelerated': 'Akselerasi GPU',
  'CPU mode': 'Mode CPU',
  'Building index…': 'Membangun indeks…',
  'Local index': 'Indeks lokal',
  'Index new media': 'Indeks media baru',
  'Rebuild': 'Bangun ulang',
  'Reset defaults': 'Kembalikan bawaan',

  // Timeline / playback
  'New sequence': 'Urutan baru',
  'New track': 'Trek baru',
  'Video track': 'Trek video',
  'Audio / music track': 'Trek audio / musik',
  'Caption track': 'Trek takarir',
  'Create a caption track first': 'Buat trek takarir terlebih dahulu',
  'Selection mode (V): drag to move / trim edges': 'Mode pilih (V): seret untuk memindah / memangkas tepi',
  'Blade mode (B): click a clip to split it there': 'Mode pisau (B): klik klip untuk memotong di titik itu',
  'Split the selected clip at the playhead (C)': 'Potong klip terpilih di posisi playhead (C)',
  'Insert placement': 'Penempatan sisip',
  'Overwrite placement': 'Penempatan timpa',
  'Detect scene changes in the selected clip': 'Deteksi pergantian adegan pada klip terpilih',
  'Snapping: on (S)': 'Snapping: aktif (S)',
  'Snapping: off (S)': 'Snapping: nonaktif (S)',
  'Recording': 'Merekam',
  'Pause (Space)': 'Jeda (Spasi)',
  'Play (Space)': 'Putar (Spasi)',
  'Zoom out timeline (⌘−)': 'Perkecil linimasa (⌘−)',
  'Zoom timeline': 'Zoom linimasa',
  'Zoom in timeline (⌘＋)': 'Perbesar linimasa (⌘＋)',
  'Fit to view (⇧Z)': 'Sesuaikan ke tampilan (⇧Z)',
  'Aspect ratio': 'Rasio aspek',
  'Content fit': 'Penyesuaian konten',
  'Letterbox': 'Letterbox',
  'Crop': 'Pangkas',
  'On': 'Aktif',
  'Off': 'Nonaktif',
  'Fullscreen preview': 'Pratinjau layar penuh',
  'Scene detection': 'Deteksi adegan',
  'Detection sensitivity': 'Sensitivitas deteksi',
  'Minimum scene interval': 'Interval minimum adegan',
  'Maximum cuts': 'Maksimum potongan',
  'Waiting': 'Menunggu',
  'Inspecting media': 'Memeriksa media',
  'Detecting scene changes': 'Mendeteksi pergantian adegan',
  'Preparing results': 'Menyiapkan hasil',
  'Detection complete': 'Deteksi selesai',
  'Detection failed': 'Deteksi gagal',
  'Not started': 'Belum dimulai',
  'Cancel detection': 'Batalkan deteksi',
  'Run again': 'Jalankan lagi',
  'Start detection': 'Mulai deteksi',
  'Cut evidence': 'Bukti potongan',
  'Before': 'Sebelum',
  'After': 'Sesudah',
  'Track locked': 'Trek terkunci',
  'Add scene markers': 'Tambah penanda adegan',
  'Split at scene changes': 'Potong pada pergantian adegan',
  'Motion tracking': 'Pelacakan gerak',
  'Experimental': 'Eksperimental',
  'Apply mode': 'Mode penerapan',
  'Start analysis': 'Mulai analisis',
  'Apply keyframes': 'Terapkan keyframe',
  'Show track': 'Tampilkan trek',
  'Hide track': 'Sembunyikan trek',
  'Unmute': 'Aktifkan suara',
  'Mute track': 'Bisukan trek',
  'Track muted': 'Trek dibisukan',
  'Unlock track': 'Buka kunci trek',
  'Rename track': 'Ganti nama trek',
  'Music': 'Musik',
  'Hide captions': 'Sembunyikan takarir',
  'Show captions': 'Tampilkan takarir',
  'Caption style & translation': 'Gaya & terjemahan takarir',
  'Delete track': 'Hapus trek',
  'Zoom': 'Zoom',
  'Voice': 'Suara',
  'Split': 'Potong',
  'Applied effects': 'Efek diterapkan',
  'Copy effects': 'Salin efek',
  'Paste effects': 'Tempel efek',
  'Ripple delete (close gap)': 'Hapus ripple (tutup celah)',
  'Marker': 'Penanda',
  'Note…': 'Catatan…',

  // Settings
  'Current version: {version}': 'Versi saat ini: {version}',
  'Check for updates': 'Periksa pembaruan',
  'Checking…': 'Memeriksa…',
  'Collapse': 'Ciutkan',
  'Expand': 'Perluas',
  'Show values': 'Tampilkan nilai',
  'Saving…': 'Menyimpan…',
  'No changes': 'Tidak ada perubahan',
  'Agent Model': 'Model Agent',
  'Agent Brain': 'Otak Agent',
  'AI Generation': 'Generasi AI',
  'Voice / TTS': 'Suara / TTS',
  'Assets · Transcription': 'Aset · Transkripsi',
  'Stock Media': 'Media stok',
  'Transcription / Script Editing': 'Transkripsi / Edit naskah',
  'Storage': 'Penyimpanan',
  'Power Tools': 'Alat lanjutan',
  'Sandbox Execution': 'Eksekusi sandbox',
  'Web Scraping': 'Pengambilan data web',
  'Model providers': 'Penyedia model',
  'Core of chat and tool calls — chat is unavailable until configured.': 'Inti chat dan pemanggilan alat — chat belum dapat dipakai sebelum model diatur.',
  'Default vendor': 'Penyedia bawaan',
  'API format': 'Format API',
  'Responses API (recommended)': 'Responses API (disarankan)',
  'Model provider': 'Penyedia model',
  'Context window (tokens)': 'Jendela konteks (token)',
  'Maximum input (tokens)': 'Input maksimum (token)',
  'Model capabilities': 'Kemampuan model',
  'Maximum output (tokens)': 'Output maksimum (token)',
  'Tool calling': 'Pemanggilan alat',
  'Image input': 'Input gambar',
  'Use model catalog': 'Gunakan katalog model',
  'Supported': 'Didukung',
  'Unsupported': 'Tidak didukung',
  'Clear override': 'Hapus override',
  'API Base URL': 'Base URL API',
  'Image model': 'Model gambar',
  'Voice model': 'Model suara',
  'Video model': 'Model video',
  'Music model': 'Model musik',
  'Cloud sync': 'Sinkronisasi cloud',
  'Bucket name': 'Nama bucket',
  'Transcription model': 'Model transkripsi',
  'Transcription language': 'Bahasa transkripsi',
  'Speaker diarization': 'Pemisahan pembicara',
  'Ask every time (default)': 'Tanya setiap kali (bawaan)',
  'Local model (free · offline)': 'Model lokal (gratis · offline)',
  'Auto-transcribe after import': 'Transkripsi otomatis setelah impor',
  'Off (manual transcription)': 'Nonaktif (transkripsi manual)',
  'Local engine only (free)': 'Hanya mesin lokal (gratis)',
  'Network proxy': 'Proxy jaringan',
  'Interface': 'Antarmuka',
  'Interface scale': 'Skala antarmuka',
  'Local models': 'Model lokal',
  'Reasoning effort': 'Tingkat penalaran',
  'Model default': 'Bawaan model',
  'Status unknown': 'Status tidak diketahui',
  'Signed in': 'Sudah masuk',
  'Signed out': 'Belum masuk',
  'Connection error': 'Kesalahan koneksi',
  'Refresh status': 'Muat ulang status',
  'Load models': 'Muat model',
  'Sign out': 'Keluar',
  'Sign in with browser': 'Masuk dengan browser',
  'Use device code': 'Gunakan kode perangkat',
  'Copied': 'Disalin',
  'Configured': 'Sudah diatur',
  'Not configured': 'Belum diatur',
  'Testing…': 'Menguji…',
  'Test connection': 'Uji koneksi',
  'Test proxy connection': 'Uji koneksi proxy',
  'Test & load models': 'Uji & muat model',
  'Choose model': 'Pilih model',
  'Clear': 'Hapus',
  'API Key (optional)': 'API Key (opsional)',
  'Proxy URL': 'URL proxy',
  'Choose Folder': 'Pilih folder',
  'Choosing…': 'Memilih…',
  'Choose media storage directory': 'Pilih folder penyimpanan media',

  'Punch': 'Hentakan',
  'Push & Pull Back': 'Dorong & Tarik Kembali',
  'Slow Push': 'Dorong Perlahan',
  'Instant': 'Instan',
  'Zoom Out': 'Perkecil',
  'Ease-In Push': 'Dorong Masuk Halus',
  'Bouncy Push': 'Dorong Memantul',
  'Snap Push': 'Dorong Cepat',
  'Pulse': 'Denyut',
  'Whip-In Push': 'Dorong Masuk Cepat',
  'Anticipation Zoom': 'Zoom Antisipasi',
  'Clean Line Wipe': 'Sapuan Garis Bersih',
  'Cross Dissolve': 'Dissolve Silang',
  'Dip to Black': 'Redup ke Hitam',
  'Flash': 'Kilat',
  'Impact Shake': 'Guncangan Dampak',
  'Luma Blend': 'Campuran Luma',
  'Organic Dissolve': 'Dissolve Organik',
  'Page Curl': 'Lipatan Halaman',
  'Rack Focus': 'Peralihan Fokus',
  'Soft Wipe': 'Sapuan Halus',
  'Whip Pan': 'Whip Pan',
  'Circle Wipe': 'Sapuan Lingkaran',

  // Sound library
  'Search sounds': 'Cari efek suara',
  'Sound groups': 'Kelompok efek suara',
  'No sounds in this group': 'Belum ada efek suara dalam kelompok ini',
  ' (nothing matches "{query}")': ' (tidak ada yang cocok dengan "{query}")',
  'Sound list': 'Daftar efek suara',
  '{desc} · Drag onto a timeline audio track': '{desc} · Seret ke trek audio linimasa',
  'Pause {name}': 'Jeda {name}',
  'Preview {name}': 'Pratinjau {name}',
  'Add to timeline: {name}': 'Tambahkan ke linimasa: {name}',
  'Add {name}': 'Tambahkan {name}',
  'Click to preview · Double-click / + / drag onto an audio track · {n} sounds total':
    'Klik untuk pratinjau · Klik dua kali / + / seret ke trek audio · total {n} efek suara',
  'UI & Motion Feedback': 'UI & umpan balik gerak',
  'Transition & Emphasis': 'Transisi & penekanan',
  'Device & Texture': 'Perangkat & tekstur',
  'Reaction & Mood': 'Reaksi & suasana',
  'Simple Whoosh': 'Whoosh sederhana',
  'Deep Short Whoosh': 'Whoosh pendek berat',
  'Airy Short Whoosh': 'Whoosh pendek ringan',
  'Long Suspense Riser': 'Riser suspense panjang',
  'Fast Suspense Riser': 'Riser suspense cepat',
  'Sharp Bass Riser': 'Riser bass tajam',
  'Short Drum Roll Sting': 'Roll drum pendek',
  'Vine Boom Impact': 'Dampak Vine Boom',
  'Dramatic Thunder Roll': 'Guntur dramatis',
  'Anime Wow Reaction': 'Reaksi wow anime',
  'Awkward Crow Flyby': 'Suara gagak canggung',
  'Sitcom Laugh Track': 'Tawa sitkom',
  'Tiny Bubble Pop': 'Pop gelembung kecil',
  'Synthetic Bubble Pop': 'Pop gelembung sintetis',
  'Keyboard Typing Loop': 'Loop ketikan keyboard',
  'Slow Dell Keyboard Typing': 'Ketikan keyboard Dell lambat',
  'Mouse Click': 'Klik mouse',
  'New Notification Ping': 'Ping notifikasi baru',
  'UI Pop-up Alert': 'Peringatan pop-up UI',
  'Phone Notification Ping': 'Ping notifikasi ponsel',
  'Sent Message Ping': 'Ping pesan terkirim',
  'Video Call Ringtone': 'Nada dering panggilan video',
  'Record Scratch Stop': 'Record scratch berhenti',
  'Record Scratch Rewind': 'Record scratch mundur',
  'Camera Shutter': 'Rana kamera',
  'Vintage Camera Shutter': 'Rana kamera vintage',
  'Short Shutter Click': 'Klik rana pendek',
  'Mechanical Clicking Loop': 'Loop klik mekanis',
  'Gear Turn Click': 'Klik putaran roda gigi',
  'Light Clock Tick': 'Detak jam ringan',
  'Clean Ding': 'Ding bersih',
  'Censor Beep': 'Bip sensor',
  'Cash Register Success': 'Bunyi kasir berhasil',
  'Glitchy TV Signal': 'Sinyal TV glitch',
  'TV Switch Off Noise': 'Suara TV dimatikan',
  'Soft Air Whoosh': 'Whoosh udara lembut',
  'Deep Impact Hit': 'Hantaman berat',
  'Crisp UI Click': 'Klik UI tajam',
  'Success Chime': 'Nada berhasil',

  // Keyboard shortcut catalog
  'Playback': 'Pemutaran',
  'Navigation': 'Navigasi',
  'Markers': 'Penanda',
  'View': 'Tampilan',
  'Play / Pause': 'Putar / Jeda',
  'Previous frame': 'Frame sebelumnya',
  'Next frame': 'Frame berikutnya',
  'Step back 1 second': 'Mundur 1 detik',
  'Step forward 1 second': 'Maju 1 detik',
  'Shuttle backward': 'Putar mundur cepat',
  'Shuttle forward': 'Putar maju cepat',
  'Shuttle pause': 'Jeda shuttle',
  'Jog back one frame': 'Mundur satu frame',
  'Jog forward one frame': 'Maju satu frame',
  'Paste Effects': 'Tempel efek',
  'Duplicate': 'Duplikat',
  'Selection Mode': 'Mode pilih',
  'Trim Edit Mode': 'Mode edit trim',
  'Slip Edit Mode': 'Mode edit slip',
  'Blade Edit Mode': 'Mode pisau',
  'Pen Edit Mode': 'Mode pena',
  'Nudge left 1 / 5 frames': 'Geser kiri 1 / 5 frame',
  'Nudge right 1 / 5 frames': 'Geser kanan 1 / 5 frame',
  'Trim start': 'Pangkas awal',
  'Trim end': 'Pangkas akhir',
  'Select clips forward': 'Pilih klip ke depan',
  'Move clip up': 'Pindahkan klip ke trek atas',
  'Move clip down': 'Pindahkan klip ke trek bawah',
  'Move left to boundary': 'Pindahkan ke batas kiri',
  'Move right to boundary': 'Pindahkan ke batas kanan',
  'Save version': 'Simpan versi',
  'Previous edit': 'Titik edit sebelumnya',
  'Next edit': 'Titik edit berikutnya',
  'Mark in': 'Tandai masuk',
  'Mark out': 'Tandai keluar',
  'Clear marks': 'Hapus tanda masuk/keluar',
  'Mark clip at playhead': 'Tandai klip di playhead',
  'Mark selection': 'Tandai pilihan',
  'Add marker': 'Tambah penanda',
  'Add marker and open dialog': 'Tambah penanda dan buka dialog',
  'Modify marker at playhead': 'Edit penanda di playhead',
  'Delete marker at playhead': 'Hapus penanda di playhead',
  'Previous marker': 'Penanda sebelumnya',
  'Next marker': 'Penanda berikutnya',
  'Snapping': 'Snapping',
  'Selection mode': 'Mode pilih',
  'Timeline zoom in': 'Perbesar linimasa',
  'Timeline zoom out': 'Perkecil linimasa',
  'Zoom timeline to fit': 'Sesuaikan linimasa ke tampilan',
  'Keyboard shortcuts': 'Pintasan keyboard',
  'Add to AI chat': 'Tambahkan ke chat AI',

  '节拍定位': 'Deteksi beat',
  '下拍定位': 'Deteksi downbeat',
  'BPM 与拍号': 'BPM & birama',
  '节拍能量': 'Energi beat',
  '音乐语义向量': 'Vektor semantik musik',
  '音乐相似度': 'Kemiripan musik',
  '画面语义向量': 'Vektor semantik visual',
  '中文画面检索': 'Pencarian visual berbasis teks',
  '重复镜头检测': 'Deteksi shot duplikat',
  '节奏分析轻量包': 'Paket analisis ritme ringan',
  '本地分析节拍、下拍、速度、拍号与节拍能量。': 'Analisis beat, downbeat, tempo, birama, dan energi beat secara lokal.',
  '音乐语义轻量包': 'Paket semantik musik ringan',
  '在本机生成音乐语义向量，用于检索与相似度匹配。': 'Membuat vektor semantik musik secara lokal untuk pencarian dan pencocokan kemiripan.',
  '画面语义轻量包': 'Paket semantik visual ringan',
  '在本机生成画面与中文文本向量，用于语义检索和重复镜头检测。': 'Membuat vektor visual dan teks secara lokal untuk pencarian semantik dan deteksi shot duplikat.',
  '简洁白字': 'Teks putih sederhana',
  '白字无底，适合口播': 'Teks putih tanpa latar, cocok untuk video berbicara',
  '黑底白字': 'Teks putih latar hitam',
  '整句黑底条，经典字幕（默认）': 'Bar hitam untuk satu kalimat, gaya subtitel klasik (bawaan)',
  '影院白字': 'Teks putih sinematik',
  '轻阴影，像正片字幕': 'Bayangan ringan seperti subtitel film',
  '清爽高亮': 'Sorotan bersih',
  '青底高亮当前词，中文友好': 'Sorot kata aktif dengan latar sian',
  '短视频撞色': 'Kontras video pendek',
  '粉红高亮，适合竖屏': 'Sorotan merah muda, cocok untuk video vertikal',
  '故事黄高亮': 'Sorotan kuning cerita',
  '白字 + 黄高亮': 'Teks putih + sorotan kuning',
  '粗描边': 'Garis tepi tebal',
  '强描边，远看也清晰': 'Garis tepi kuat agar tetap jelas dari jauh',
  '工作室白底': 'Latar putih studio',
  '深字浅底，干净': 'Teks gelap di latar terang, bersih',
  '白卡片': 'Kartu putih',
  '灰字白底卡片': 'Teks abu-abu pada kartu putih',
  '杂志黄标': 'Label kuning majalah',
  '黑字黄高亮，文艺': 'Teks hitam dengan sorotan kuning bergaya editorial',
  '气泡大字': 'Teks besar gelembung',
  '大号撞色，强调词': 'Teks besar berkontras untuk menekankan kata',
  '绿底堆叠': 'Tumpukan latar hijau',
  '绿色高亮、可堆叠': 'Sorotan hijau dan dapat ditumpuk',
  '黑白堆叠': 'Tumpukan hitam-putih',
  '黑字白底，堆叠两行': 'Teks hitam di latar putih, dua baris bertumpuk',
  '黄字大标题': 'Judul besar kuning',
  '超大字 + 黄高亮': 'Teks sangat besar + sorotan kuning',
  '霓虹大写': 'Huruf kapital neon',
  '全大写 + 彩边光': 'Huruf kapital dengan cahaya tepi berwarna',
  '灰调衬线': 'Serif abu-abu',
  '灰字，偏设计感': 'Teks abu-abu dengan gaya desain',
  '奢华金': 'Emas mewah',
  '金色字，典雅': 'Teks emas yang elegan',
  '暗夜红': 'Merah malam',
  '暗调 + 红高亮': 'Nuansa gelap + sorotan merah',
  '工坊红底': 'Latar merah studio',
  '深字红底高亮': 'Teks gelap dengan sorotan latar merah',
  '产品绿标': 'Label hijau produk',
  '青白字 + 荧光绿': 'Teks sian-putih + hijau neon',
  '信号青': 'Sian teknologi',
  '科技风青绿高亮': 'Sorotan sian-hijau bergaya teknologi',
  '得意黑': 'Hitam display',
  '中文展示字体': 'Font display',
  '行动号召': 'Ajakan bertindak',
  '数据可视化': 'Visualisasi data',
  '信息图表': 'Infografik',
  '下三分之一字幕': 'Lower third',
  '引用卡片': 'Kartu kutipan',
  '社交界面': 'UI sosial',
  '出镜叠加': 'Overlay talking-head',
  '文字特效': 'Efek teks',
  '标题卡片': 'Kartu judul',
  '社交媒体': 'Media sosial',
  '竖屏自媒体': 'Video vertikal / Shorts',
  '口播场景': 'Adegan talking-head',
  '插件': 'Plugin',
  '扩展': 'Ekstensi',
  '未分类': 'Belum dikategorikan',
  'MG 动画': 'Motion graphics',
  '收藏': 'Favorit',
  '最近': 'Terbaru',
  '热门': 'Populer',
  '还没有收藏的模板。将鼠标移到卡片上点 ★ 收藏。': 'Belum ada template favorit. Arahkan mouse ke kartu lalu klik ★ untuk memfavoritkan.',
  '还没有最近使用的模板。点卡片右上角＋或拖到时间线后会出现在这里。': 'Belum ada template yang baru digunakan. Klik ＋ pada kartu atau seret ke linimasa agar muncul di sini.',
  '添加到时间线': 'Tambahkan ke linimasa',
  '用 AI 生成': 'Buat dengan AI',
  '确认删除': 'Konfirmasi hapus',
  '取消': 'Batal',
  '从资源库列表移除(本地隐藏);时间线已用片段不受影响': 'Hapus dari daftar pustaka (disembunyikan secara lokal); klip yang sudah ada di linimasa tidak terpengaruh',
  '删除': 'Hapus',
  '选择创作工作流会约束 Agent 的规划与工具调用；激活后下一条消息按该工作流执行。': 'Memilih alur kerja kreatif akan memandu perencanaan dan penggunaan alat Agent; pesan berikutnya dijalankan dengan alur tersebut.',
  '搜索技能（名称 / 说明）': 'Cari skill (nama / deskripsi)',
  '当前：{name}': 'Aktif: {name}',
  '点击取消创作模式，回到自由创作': 'Klik untuk keluar dari mode kreatif dan kembali ke mode bebas',
  '专业工作流': 'Alur kerja profesional',
  '没有匹配的技能': 'Tidak ada skill yang cocok',
  '自定义': 'Kustom',
  '修改技能': 'Edit skill',
  '删除技能': 'Hapus skill',
  '确认?': 'Konfirmasi?',
  '提示：也可在聊天输入框用 /skill:名称 快速激活，或用「技能创作器」创建自己的技能。': 'Tip: gunakan /skill:nama di kotak chat untuk mengaktifkan cepat, atau gunakan pembuat skill untuk membuat skill sendiri.',
  '名称不能为空': 'Nama tidak boleh kosong',
  '名称': 'Nama',
  '说明': 'Deskripsi',
  '正文（Markdown，含 frontmatter）': 'Isi (Markdown, termasuk frontmatter)',
  '保存中…': 'Menyimpan…',
  '保存': 'Simpan',

  // Chinese source keys that are used outside the regular dictionary path.
  '选择素材保存目录': 'Pilih folder penyimpanan media',
  '选择导出目录': 'Pilih folder ekspor',
  '所选导出目录不可用': 'Folder ekspor yang dipilih tidak dapat digunakan',
  '选择导出文件': 'Pilih file ekspor',
  '导出文件名无效': 'Nama file ekspor tidak valid',
  '文字稿': 'Transkrip',
};

const TECHNICAL_EXACT = new Set([
  'Gemini', 'Google Gemini', 'OpenAI', 'Anthropic', 'FFmpeg', 'FFprobe',
  'FPS', 'SRT', 'MCP', 'GPU', 'CPU', 'JSON', 'MP4', 'MOV', 'WebM',
  'API', 'API Key', 'Base URL', 'URL', 'HTTP', 'HTTPS', 'WebGPU',
  'Whisper', 'Remotion', 'Electron', 'SQLite', 'ONNX',
  'Google · Gemini', 'Anthropic · Claude', 'GitHub Copilot', 'OpenAI · Codex',
  'Moonshot AI · Kimi', 'Alibaba Cloud · Qwen', 'DeepSeek', 'Mistral AI',
  'BytePlus · ModelArk', 'MiniMax', 'xAI · Grok', 'OpenRouter', 'OFox',
  'OrcaRouter', 'Ollama (Local)', 'LM Studio (Local)',
]);

const HAS_CJK = /[\u3400-\u9FFF\uF900-\uFAFF]/;
const URL_OR_PATH = /^(?:https?:\/\/|file:|[A-Za-z]:[\\/]|\/|\.\.?[\\/])/;
const MODELISH = /^(?:[A-Za-z0-9_.:+/@-]+)(?:\s+[A-Za-z0-9_.:+/@-]+){0,2}$/;

function replaceCommonEnglish(input: string): string {
  let out = input;
  const replacements: Array<[RegExp, string]> = [
    [/\bExporting\b/gi, 'Mengekspor'],
    [/\bExport\b/gi, 'Ekspor'],
    [/\bImporting\b/gi, 'Mengimpor'],
    [/\bImport\b/gi, 'Impor'],
    [/\bSettings\b/gi, 'Pengaturan'],
    [/\bProject(s)?\b/gi, 'Proyek'],
    [/\bTimeline\b/gi, 'Linimasa'],
    [/\bTranscript\b/gi, 'Transkrip'],
    [/\bCaption(s)?\b/gi, 'Takarir'],
    [/\bSubtitle(s)?\b/gi, 'Subtitel'],
    [/\bDelete\b/gi, 'Hapus'],
    [/\bRemove\b/gi, 'Hapus'],
    [/\bAdd\b/gi, 'Tambah'],
    [/\bSave\b/gi, 'Simpan'],
    [/\bCancel\b/gi, 'Batal'],
    [/\bClose\b/gi, 'Tutup'],
    [/\bOpen\b/gi, 'Buka'],
    [/\bBack\b/gi, 'Kembali'],
    [/\bRetry\b/gi, 'Coba lagi'],
    [/\bLoading\b/gi, 'Memuat'],
    [/\bProcessing\b/gi, 'Memproses'],
    [/\bFailed\b/gi, 'Gagal'],
    [/\bError\b/gi, 'Kesalahan'],
    [/\bWarning\b/gi, 'Peringatan'],
    [/\bSelect\b/gi, 'Pilih'],
    [/\bDirectory\b/gi, 'Folder'],
    [/\bFolder\b/gi, 'Folder'],
    [/\bFile\b/gi, 'File'],
    [/\bModel\b/gi, 'Model'],
    [/\bProvider\b/gi, 'Penyedia'],
    [/\bReasoning\b/gi, 'Penalaran'],
    [/\bLanguage\b/gi, 'Bahasa'],
    [/\bHistory\b/gi, 'Riwayat'],
    [/\bWindow\b/gi, 'Jendela'],
  ];
  for (const [pattern, replacement] of replacements) out = out.replace(pattern, replacement);
  return out;
}

function containsObviousEnglishSentence(text: string): boolean {
  return /\b(the|this|that|with|from|for|and|or|your|you|is|are|was|were|to|of|in|on|when|while|cannot|could|should|please)\b/i.test(text);
}

function looksIndonesian(text: string): boolean {
  return /\b(yang|dan|atau|untuk|dengan|dari|ke|di|pada|ini|itu|sudah|belum|bisa|dapat|pilih|hapus|simpan|buka|tutup|masukkan|gunakan|pengaturan|model|proyek|folder|media|klip|trek|linimasa|bahasa|koneksi|coba|gagal|berhasil|sedang|setelah|sebelum|hingga|pisahkan|koma|utama|opsional|bawaan)\b/i.test(text);
}

export function indonesianUiText(input: unknown, original?: unknown): string {
  const rawOriginal = typeof original === 'string' ? original.trim() : '';
  if (rawOriginal && DIRECT[rawOriginal]) return DIRECT[rawOriginal]!;

  const raw = typeof input === 'string' ? input.trim() : '';
  if (!raw) return '';
  if (DIRECT[raw]) return DIRECT[raw]!;
  if (TECHNICAL_EXACT.has(raw)) return raw;
  if (URL_OR_PATH.test(raw)) return raw;
  if (!/[A-Za-z\u3400-\u9FFF\uF900-\uFAFF]/.test(raw)) return raw;
  if (!HAS_CJK.test(raw) && looksIndonesian(raw)) return raw;

  if (HAS_CJK.test(raw)) return 'Teks antarmuka belum diterjemahkan';

  const converted = replaceCommonEnglish(raw);
  if (converted !== raw && !containsObviousEnglishSentence(converted)) return converted;

  // Short model IDs / format names are technical identifiers, not UI prose.
  if (MODELISH.test(raw) && (/[0-9_.:/@-]/.test(raw) || raw.length <= 5)) return raw;

  // Never leak an untranslated foreign-language sentence into the MiniCut UI.
  return 'Teks antarmuka belum diterjemahkan';
}

export function containsCjk(input: unknown): boolean {
  return typeof input === 'string' && HAS_CJK.test(input);
}
