/**
 * MiniCut Indonesian-only UI translation bridge.
 *
 * OpenChatCut uses Chinese source strings as i18n keys. MiniCut never renders
 * those keys directly. We resolve through the upstream English dictionary and
 * then convert supported UI copy to Indonesian. Unknown non-technical copy is
 * replaced with a safe Indonesian placeholder instead of leaking another
 * language into the interface.
 */

const DIRECT: Record<string, string> = {
  // Top bar / common actions
  'Switch UI language': 'Bahasa antarmuka',
  'Back to projects': 'Kembali ke proyek',
  'Double-click to rename': 'Klik dua kali untuk mengganti nama',
  'Edit keyboard shortcuts': 'Edit pintasan keyboard',
  'Undo': 'Urungkan',
  'Redo': 'Ulangi',
  'Design style (brand)': 'Gaya desain (merek)',
  'Version History': 'Riwayat versi',
  'Toggle panel layout': 'Ubah tata letak panel',
  'Export MP4': 'Ekspor MP4',
  'Exporting…': 'Mengekspor…',
  'Export': 'Ekspor',
  'Account': 'Akun',
  'Window controls': 'Kontrol jendela',
  'Close window': 'Tutup jendela',
  'Minimize window': 'Minimalkan jendela',
  'Zoom window': 'Perbesar jendela',
  'Settings': 'Pengaturan',
  'Close': 'Tutup',
  'Cancel': 'Batal',
  'Save': 'Simpan',
  'Open': 'Buka',
  'Delete': 'Hapus',
  'Remove': 'Hapus',
  'Add': 'Tambah',
  'Edit': 'Edit',
  'Copy': 'Salin',
  'Paste': 'Tempel',
  'Cut': 'Potong',
  'Search': 'Cari',
  'Reset': 'Atur ulang',
  'Retry': 'Coba lagi',
  'Continue': 'Lanjutkan',
  'Confirm': 'Konfirmasi',
  'Apply': 'Terapkan',
  'Done': 'Selesai',
  'Loading…': 'Memuat…',
  'Processing…': 'Memproses…',
  'Project': 'Proyek',
  'Projects': 'Proyek',
  'New project': 'Proyek baru',
  'Media': 'Media',
  'Timeline': 'Linimasa',
  'Transcript': 'Transkrip',
  'Captions': 'Takarir',
  'Subtitle': 'Subtitel',
  'Subtitles': 'Subtitel',
  'Audio': 'Audio',
  'Video': 'Video',
  'Image': 'Gambar',
  'Images': 'Gambar',
  'Text': 'Teks',
  'Effects': 'Efek',
  'Transitions': 'Transisi',
  'Speed': 'Kecepatan',
  'Volume': 'Volume',
  'Opacity': 'Opasitas',
  'Position': 'Posisi',
  'Rotation': 'Rotasi',
  'Scale': 'Skala',
  'Duration': 'Durasi',
  'Start': 'Mulai',
  'End': 'Akhir',
  'Name': 'Nama',
  'Type': 'Jenis',
  'Status': 'Status',
  'Error': 'Kesalahan',
  'Warning': 'Peringatan',
  'Success': 'Berhasil',
  'Failed': 'Gagal',
  'Ready': 'Siap',
  'Enabled': 'Aktif',
  'Disabled': 'Nonaktif',
  'Auto': 'Otomatis',
  'Manual': 'Manual',
  'Default': 'Bawaan',
  'Advanced': 'Lanjutan',
  'General': 'Umum',
  'Language': 'Bahasa',
  'Model': 'Model',
  'Provider': 'Penyedia',
  'Agent': 'Agent',
  'AI Chat': 'Chat AI',
  'Reasoning': 'Penalaran',
  'API Key': 'API Key',
  'Base URL': 'Base URL',
  'Export directory': 'Folder ekspor',
  'Select export directory': 'Pilih folder ekspor',
  'Select export file': 'Pilih file ekspor',
  'Select media save directory': 'Pilih folder penyimpanan media',
  'No clips were modified.': 'Tidak ada klip yang diubah.',
  'Voice isolation failed; no clips were modified.': 'Pemisahan suara gagal; tidak ada klip yang diubah.',
  'Loudness analysis failed; no clips were modified.': 'Analisis kenyaringan gagal; tidak ada klip yang diubah.',
  'Source media changed; the previous voice separation result was discarded. Retry.':
    'Media sumber berubah; hasil pemisahan suara sebelumnya dibuang. Coba lagi.',
  // Project / editor shell
  'Loading project…': 'Memuat proyek…',
  'Loading editor…': 'Memuat editor…',
  'Project not found, going back…': 'Proyek tidak ditemukan, kembali…',
  'Project data is temporarily unreadable': 'Data proyek sementara tidak dapat dibaca',
  'Project save failed. Retry before closing or switching projects.': 'Penyimpanan proyek gagal. Coba lagi sebelum menutup atau berpindah proyek.',
  'The project is still unsaved, so navigation was blocked. Keep editing to retry.': 'Proyek belum tersimpan, jadi perpindahan halaman diblokir. Lanjutkan mengedit untuk mencoba lagi.',
  'Just now': 'Baru saja',
  '{n} min ago': '{n} menit lalu',
  '{n} hr ago': '{n} jam lalu',
  '{n} d ago': '{n} hari lalu',
  'Generation Tasks': 'Tugas generasi',
  'Resume Tasks': 'Lanjutkan tugas',
  'Loading tasks…': 'Memuat tugas…',
  'No generation tasks': 'Tidak ada tugas generasi',
  'Pending': 'Menunggu',
  'Running': 'Berjalan',
  'Completed': 'Selesai',
  'Not Found': 'Tidak ditemukan',
  'Check Progress': 'Periksa progres',
  'Open Result': 'Buka hasil',
  'Retry Recoverable Tasks': 'Coba ulang tugas yang bisa dipulihkan',
  'Settings · API Keys': 'Pengaturan · API Key',
  'Configure a model to start using the Agent': 'Atur model untuk mulai menggunakan Agent',
  'Configure any cloud or local model to use conversational editing in the editor.': 'Atur model cloud atau lokal untuk memakai pengeditan percakapan di editor.',
  'Configure Model': 'Atur model',
  'Search projects': 'Cari proyek',
  'Clear search': 'Hapus pencarian',
  'No projects match “{query}”': 'Tidak ada proyek yang cocok dengan “{query}”',
  'New Project': 'Proyek baru',
  'Open {name}': 'Buka {name}',
  'Confirm Delete': 'Konfirmasi hapus',
  'Rename': 'Ganti nama',
  'Duplicate': 'Duplikat',
  'Import Project': 'Impor proyek',
  'Export History': 'Riwayat ekspor',
  'No exports yet': 'Belum ada ekspor',
  'Open Folder': 'Buka folder',
  'Clear History': 'Hapus riwayat',
  'No versions saved yet': 'Belum ada versi tersimpan',
  'Restore': 'Pulihkan',
  'Delete this version': 'Hapus versi ini',
  'Version name': 'Nama versi',
  'Save Current Version': 'Simpan versi saat ini',
  'Preview': 'Pratinjau',
  'Safe Area': 'Area aman',
  'Preview quality': 'Kualitas pratinjau',
  'High quality': 'Kualitas tinggi',
  'Smooth': 'Lancar',
  'Drop media here': 'Letakkan media di sini',
  'Previous keyframe': 'Keyframe sebelumnya',
  'Next keyframe': 'Keyframe berikutnya',
  'Add a keyframe at the playhead': 'Tambah keyframe di playhead',
  'Delete the keyframe at the playhead': 'Hapus keyframe di playhead',
  'Linear': 'Linear',
  'Ease In': 'Ease In',
  'Ease Out': 'Ease Out',
  'Ease In-Out': 'Ease In-Out',
  'Font Size': 'Ukuran font',
  'Color': 'Warna',
  'Align': 'Perataan',
  'Left': 'Kiri',
  'Center': 'Tengah',
  'Right': 'Kanan',
  'Weight': 'Ketebalan',
  'Regular': 'Normal',
  'Bold': 'Tebal',
  'Crop Left': 'Potong kiri',
  'Crop Right': 'Potong kanan',
  'Crop Top': 'Potong atas',
  'Crop Bottom': 'Potong bawah',
  'Fade In': 'Fade masuk',
  'Fade Out': 'Fade keluar',
  'Keyframes': 'Keyframe',
  'Brightness': 'Kecerahan',
  'Contrast': 'Kontras',
  'Saturation': 'Saturasi',
  'Blur': 'Blur',
  'Auto Color': 'Warna otomatis',

  // Agent / chat
  'Expand OpenChatCut Agent': 'Perluas Agent MiniCut',
  'Collapse OpenChatCut Agent': 'Ciutkan Agent MiniCut',
  'Clear chat': 'Hapus chat',
  'Agent workspace': 'Ruang kerja Agent',
  'Jump to top': 'Ke paling atas',
  'Jump to bottom': 'Ke paling bawah',
  'Start here': 'Mulai di sini',
  'Start with an editing goal': 'Mulai dengan tujuan pengeditan',
  'Choose a workflow, or describe the finished video you want.': 'Pilih alur kerja atau jelaskan hasil video yang kamu inginkan.',
  'Thinking…': 'Berpikir…',
  'Describe what you want to create...': 'Jelaskan apa yang ingin kamu buat...',
  'Tell the AI what to change — @ to reference assets': 'Beri tahu AI apa yang harus diubah — gunakan @ untuk merujuk aset',
  'Import failed': 'Impor gagal',
  'Agent change log': 'Riwayat perubahan Agent',
  'Resend': 'Kirim ulang',
  'Server-side': 'Sisi server',
  'Awaiting approval': 'Menunggu persetujuan',
  'Awaiting reply': 'Menunggu jawaban',
  'Cancelled': 'Dibatalkan',
  'Interrupted': 'Terputus',
  'Unknown status': 'Status tidak diketahui',
  'Context and tools': 'Konteks dan alat',
  'Input': 'Input',
  'Output': 'Output',
  'System': 'Sistem',
  'History': 'Riwayat',
  'Active tools': 'Alat aktif',
  'Tool schemas': 'Skema alat',
  'Model requests': 'Permintaan model',
  'Total input': 'Total input',
  'Total output': 'Total output',
  'Retries': 'Percobaan ulang',
  'Validation failed': 'Validasi gagal',
  'Denied': 'Ditolak',
  'Unknown tool': 'Alat tidak dikenal',
  'Approvals': 'Persetujuan',
  'Original operation': 'Operasi asli',
  'Operation ID': 'ID operasi',
  'Action': 'Aksi',
  'Command': 'Perintah',
  'File path': 'Path file',
  'Path': 'Path',
  'Repository': 'Repositori',
  'Install directory': 'Folder instalasi',
  'Skill': 'Skill',
  'Asset ID': 'ID aset',
  'Project ID': 'ID proyek',
  'Template ID': 'ID template',
  'Version ID': 'ID versi',
  'Prompt': 'Prompt',
  'Format': 'Format',
  'Codec': 'Codec',
  'Resolution': 'Resolusi',
  'Output directory': 'Folder output',
  'Quick actions': 'Aksi cepat',
  'Quick actions…': 'Aksi cepat…',
  'Remove filler words': 'Hapus kata pengisi',
  'Remove silence': 'Hapus bagian hening',
  'Jump cut': 'Jump cut',
  'Generate captions': 'Buat takarir',
  'Normalize loudness': 'Normalkan kenyaringan',
  'Landscape to portrait': 'Lanskap ke potret',
  'Clean talking-head edit': 'Rapikan video talking-head',
  'Remove pauses and filler, then sync captions': 'Hapus jeda dan kata pengisi, lalu sinkronkan takarir',
  'Motion package': 'Paket motion',
  'Titles, info cards, and transitions': 'Judul, kartu info, dan transisi',
  'Long-form highlights': 'Sorotan video panjang',
  'Find highlights and reshape them as shorts': 'Cari sorotan dan ubah menjadi video pendek',
  'Product story': 'Cerita produk',
  'AI visual': 'Visual AI',
  'Knowledge video': 'Video pengetahuan',

  // Media pool
  'Search media': 'Cari media',
  'Upload media': 'Unggah media',
  'Add solid color': 'Tambah warna solid',
  'New folder': 'Folder baru',
  'Sort media': 'Urutkan media',
  'Newest first': 'Terbaru dulu',
  'Name A–Z': 'Nama A–Z',
  'Filter media': 'Filter media',
  'All': 'Semua',
  'Document': 'Dokumen',
  'Other files': 'File lain',
  'Favorite': 'Favorit',
  'Relink Offline Media': 'Hubungkan ulang media offline',
  'Relink file': 'Hubungkan ulang file',
  'Back to parent folder': 'Kembali ke folder induk',
  'Rename folder': 'Ganti nama folder',
  'Delete empty folder': 'Hapus folder kosong',
  'Clear selection': 'Hapus pilihan',
  'Select all': 'Pilih semua',
  'Deselect all': 'Batalkan semua pilihan',
  'Selected {n}': '{n} dipilih',
  'Add to timeline': 'Tambahkan ke linimasa',
  'Download original': 'Unduh file asli',
  'Move selected assets': 'Pindahkan aset terpilih',
  'Move to…': 'Pindahkan ke…',
  'This folder is empty': 'Folder ini kosong',
  'Import media or drag files here.': 'Impor media atau seret file ke sini.',
  'Used on a timeline': 'Dipakai di linimasa',
  'Delete In-Use Media': 'Hapus media yang sedang dipakai',
  'Asset display name': 'Nama tampilan aset',
  'Batch rename media': 'Ganti nama media massal',
  'Copy selected': 'Salin yang dipilih',
  'Paste copies': 'Tempel salinan',
  'Paste media': 'Tempel media',
  'Convert': 'Konversi',
  'Clean Up Media': 'Bersihkan media',
  'Scanning… (collecting references per project)': 'Memindai… (mengumpulkan referensi tiap proyek)',
  'Deleting…': 'Menghapus…',
  'Delete selected': 'Hapus yang dipilih',
  'Uploading': 'Mengunggah',
  'Upload canceled': 'Unggahan dibatalkan',
  'File too large to upload': 'File terlalu besar untuk diunggah',
  'Upload from phone': 'Unggah dari ponsel',
  'Phone upload QR code': 'Kode QR unggahan ponsel',
  'Generating QR code…': 'Membuat kode QR…',
  'Local network address': 'Alamat jaringan lokal',
  'Copy link': 'Salin tautan',
  'Semantic search': 'Pencarian semantik',
  'Local semantic search': 'Pencarian semantik lokal',
  'Media never leaves this device': 'Media tidak pernah keluar dari perangkat ini',
  'Search by visual content': 'Cari berdasarkan isi visual',
  'Enable local model': 'Aktifkan model lokal',
  'Disable local model': 'Nonaktifkan model lokal',
  'GPU accelerated': 'Akselerasi GPU',
  'CPU mode': 'Mode CPU',
  'Building index…': 'Membangun indeks…',
  'Local index': 'Indeks lokal',
  'Index new media': 'Indeks media baru',
  'Rebuild': 'Bangun ulang',
  'Reset defaults': 'Kembalikan bawaan',

  // Timeline / playback
  'New sequence': 'Urutan baru',
  'New track': 'Trek baru',
  'Video track': 'Trek video',
  'Audio / music track': 'Trek audio / musik',
  'Caption track': 'Trek takarir',
  'Create a caption track first': 'Buat trek takarir terlebih dahulu',
  'Selection mode (V): drag to move / trim edges': 'Mode pilih (V): seret untuk memindah / memangkas tepi',
  'Blade mode (B): click a clip to split it there': 'Mode pisau (B): klik klip untuk memotong di titik itu',
  'Split the selected clip at the playhead (C)': 'Potong klip terpilih di posisi playhead (C)',
  'Insert placement': 'Penempatan sisip',
  'Overwrite placement': 'Penempatan timpa',
  'Detect scene changes in the selected clip': 'Deteksi pergantian adegan pada klip terpilih',
  'Snapping: on (S)': 'Snapping: aktif (S)',
  'Snapping: off (S)': 'Snapping: nonaktif (S)',
  'Recording': 'Merekam',
  'Pause (Space)': 'Jeda (Spasi)',
  'Play (Space)': 'Putar (Spasi)',
  'Zoom out timeline (⌘−)': 'Perkecil linimasa (⌘−)',
  'Zoom timeline': 'Zoom linimasa',
  'Zoom in timeline (⌘＋)': 'Perbesar linimasa (⌘＋)',
  'Fit to view (⇧Z)': 'Sesuaikan ke tampilan (⇧Z)',
  'Aspect ratio': 'Rasio aspek',
  'Content fit': 'Penyesuaian konten',
  'Letterbox': 'Letterbox',
  'Crop': 'Pangkas',
  'On': 'Aktif',
  'Off': 'Nonaktif',
  'Fullscreen preview': 'Pratinjau layar penuh',
  'Scene detection': 'Deteksi adegan',
  'Detection sensitivity': 'Sensitivitas deteksi',
  'Minimum scene interval': 'Interval minimum adegan',
  'Maximum cuts': 'Maksimum potongan',
  'Waiting': 'Menunggu',
  'Inspecting media': 'Memeriksa media',
  'Detecting scene changes': 'Mendeteksi pergantian adegan',
  'Preparing results': 'Menyiapkan hasil',
  'Detection complete': 'Deteksi selesai',
  'Detection failed': 'Deteksi gagal',
  'Not started': 'Belum dimulai',
  'Cancel detection': 'Batalkan deteksi',
  'Run again': 'Jalankan lagi',
  'Start detection': 'Mulai deteksi',
  'Cut evidence': 'Bukti potongan',
  'Before': 'Sebelum',
  'After': 'Sesudah',
  'Track locked': 'Trek terkunci',
  'Add scene markers': 'Tambah penanda adegan',
  'Split at scene changes': 'Potong pada pergantian adegan',
  'Motion tracking': 'Pelacakan gerak',
  'Experimental': 'Eksperimental',
  'Apply mode': 'Mode penerapan',
  'Start analysis': 'Mulai analisis',
  'Apply keyframes': 'Terapkan keyframe',
  'Show track': 'Tampilkan trek',
  'Hide track': 'Sembunyikan trek',
  'Unmute': 'Aktifkan suara',
  'Mute track': 'Bisukan trek',
  'Track muted': 'Trek dibisukan',
  'Unlock track': 'Buka kunci trek',
  'Rename track': 'Ganti nama trek',
  'Music': 'Musik',
  'Hide captions': 'Sembunyikan takarir',
  'Show captions': 'Tampilkan takarir',
  'Caption style & translation': 'Gaya & terjemahan takarir',
  'Delete track': 'Hapus trek',
  'Zoom': 'Zoom',
  'Voice': 'Suara',
  'Split': 'Potong',
  'Applied effects': 'Efek diterapkan',
  'Copy effects': 'Salin efek',
  'Paste effects': 'Tempel efek',
  'Ripple delete (close gap)': 'Hapus ripple (tutup celah)',
  'Marker': 'Penanda',
  'Note…': 'Catatan…',

  // Settings
  'Current version: {version}': 'Versi saat ini: {version}',
  'Check for updates': 'Periksa pembaruan',
  'Checking…': 'Memeriksa…',
  'Collapse': 'Ciutkan',
  'Expand': 'Perluas',
  'Show values': 'Tampilkan nilai',
  'Saving…': 'Menyimpan…',
  'No changes': 'Tidak ada perubahan',
  'Agent Model': 'Model Agent',
  'Agent Brain': 'Otak Agent',
  'AI Generation': 'Generasi AI',
  'Voice / TTS': 'Suara / TTS',
  'Assets · Transcription': 'Aset · Transkripsi',
  'Stock Media': 'Media stok',
  'Transcription / Script Editing': 'Transkripsi / Edit naskah',
  'Storage': 'Penyimpanan',
  'Power Tools': 'Alat lanjutan',
  'Sandbox Execution': 'Eksekusi sandbox',
  'Web Scraping': 'Pengambilan data web',
  'Model providers': 'Penyedia model',
  'Core of chat and tool calls — chat is unavailable until configured.': 'Inti chat dan pemanggilan alat — chat belum dapat dipakai sebelum model diatur.',
  'Default vendor': 'Penyedia bawaan',
  'API format': 'Format API',
  'Responses API (recommended)': 'Responses API (disarankan)',
  'Model provider': 'Penyedia model',
  'Context window (tokens)': 'Jendela konteks (token)',
  'Maximum input (tokens)': 'Input maksimum (token)',
  'Model capabilities': 'Kemampuan model',
  'Maximum output (tokens)': 'Output maksimum (token)',
  'Tool calling': 'Pemanggilan alat',
  'Image input': 'Input gambar',
  'Use model catalog': 'Gunakan katalog model',
  'Supported': 'Didukung',
  'Unsupported': 'Tidak didukung',
  'Clear override': 'Hapus override',
  'API Base URL': 'Base URL API',
  'Image model': 'Model gambar',
  'Voice model': 'Model suara',
  'Video model': 'Model video',
  'Music model': 'Model musik',
  'Cloud sync': 'Sinkronisasi cloud',
  'Bucket name': 'Nama bucket',
  'Transcription model': 'Model transkripsi',
  'Transcription language': 'Bahasa transkripsi',
  'Speaker diarization': 'Pemisahan pembicara',
  'Ask every time (default)': 'Tanya setiap kali (bawaan)',
  'Local model (free · offline)': 'Model lokal (gratis · offline)',
  'Auto-transcribe after import': 'Transkripsi otomatis setelah impor',
  'Off (manual transcription)': 'Nonaktif (transkripsi manual)',
  'Local engine only (free)': 'Hanya mesin lokal (gratis)',
  'Network proxy': 'Proxy jaringan',
  'Interface': 'Antarmuka',
  'Interface scale': 'Skala antarmuka',
  'Local models': 'Model lokal',
  'Reasoning effort': 'Tingkat penalaran',
  'Model default': 'Bawaan model',
  'Status unknown': 'Status tidak diketahui',
  'Signed in': 'Sudah masuk',
  'Signed out': 'Belum masuk',
  'Connection error': 'Kesalahan koneksi',
  'Refresh status': 'Muat ulang status',
  'Load models': 'Muat model',
  'Sign out': 'Keluar',
  'Sign in with browser': 'Masuk dengan browser',
  'Use device code': 'Gunakan kode perangkat',
  'Copied': 'Disalin',
  'Configured': 'Sudah diatur',
  'Not configured': 'Belum diatur',
  'Testing…': 'Menguji…',
  'Test connection': 'Uji koneksi',
  'Test proxy connection': 'Uji koneksi proxy',
  'Test & load models': 'Uji & muat model',
  'Choose model': 'Pilih model',
  'Clear': 'Hapus',
  'API Key (optional)': 'API Key (opsional)',
  'Proxy URL': 'URL proxy',
  'Choose Folder': 'Pilih folder',
  'Choosing…': 'Memilih…',
  'Choose media storage directory': 'Pilih folder penyimpanan media',

  'Punch': 'Hentakan',
  'Push & Pull Back': 'Dorong & Tarik Kembali',
  'Slow Push': 'Dorong Perlahan',
  'Instant': 'Instan',
  'Zoom Out': 'Perkecil',
  'Ease-In Push': 'Dorong Masuk Halus',
  'Bouncy Push': 'Dorong Memantul',
  'Snap Push': 'Dorong Cepat',
  'Pulse': 'Denyut',
  'Whip-In Push': 'Dorong Masuk Cepat',
  'Anticipation Zoom': 'Zoom Antisipasi',
  'Clean Line Wipe': 'Sapuan Garis Bersih',
  'Cross Dissolve': 'Dissolve Silang',
  'Dip to Black': 'Redup ke Hitam',
  'Flash': 'Kilat',
  'Impact Shake': 'Guncangan Dampak',
  'Luma Blend': 'Campuran Luma',
  'Organic Dissolve': 'Dissolve Organik',
  'Page Curl': 'Lipatan Halaman',
  'Rack Focus': 'Peralihan Fokus',
  'Soft Wipe': 'Sapuan Halus',
  'Whip Pan': 'Whip Pan',
  'Circle Wipe': 'Sapuan Lingkaran',

  // Chinese source keys that are used outside the regular dictionary path.
  '选择素材保存目录': 'Pilih folder penyimpanan media',
  '选择导出目录': 'Pilih folder ekspor',
  '所选导出目录不可用': 'Folder ekspor yang dipilih tidak dapat digunakan',
  '选择导出文件': 'Pilih file ekspor',
  '导出文件名无效': 'Nama file ekspor tidak valid',
  '文字稿': 'Transkrip',
};

const TECHNICAL_EXACT = new Set([
  'Gemini', 'Google Gemini', 'OpenAI', 'Anthropic', 'FFmpeg', 'FFprobe',
  'FPS', 'SRT', 'MCP', 'GPU', 'CPU', 'JSON', 'MP4', 'MOV', 'WebM',
  'API', 'API Key', 'Base URL', 'URL', 'HTTP', 'HTTPS', 'WebGPU',
  'Whisper', 'Remotion', 'Electron', 'SQLite', 'ONNX',
  'Google · Gemini', 'Anthropic · Claude', 'GitHub Copilot', 'OpenAI · Codex',
  'Moonshot AI · Kimi', 'Alibaba Cloud · Qwen', 'DeepSeek', 'Mistral AI',
  'BytePlus · ModelArk', 'MiniMax', 'xAI · Grok', 'OpenRouter', 'OFox',
  'OrcaRouter', 'Ollama (Local)', 'LM Studio (Local)',
]);

const HAS_CJK = /[\u3400-\u9FFF\uF900-\uFAFF]/;
const URL_OR_PATH = /^(?:https?:\/\/|file:|[A-Za-z]:[\\/]|\/|\.\.?[\\/])/;
const MODELISH = /^(?:[A-Za-z0-9_.:+/@-]+)(?:\s+[A-Za-z0-9_.:+/@-]+){0,2}$/;

function replaceCommonEnglish(input: string): string {
  let out = input;
  const replacements: Array<[RegExp, string]> = [
    [/\bExporting\b/gi, 'Mengekspor'],
    [/\bExport\b/gi, 'Ekspor'],
    [/\bImporting\b/gi, 'Mengimpor'],
    [/\bImport\b/gi, 'Impor'],
    [/\bSettings\b/gi, 'Pengaturan'],
    [/\bProject(s)?\b/gi, 'Proyek'],
    [/\bTimeline\b/gi, 'Linimasa'],
    [/\bTranscript\b/gi, 'Transkrip'],
    [/\bCaption(s)?\b/gi, 'Takarir'],
    [/\bSubtitle(s)?\b/gi, 'Subtitel'],
    [/\bDelete\b/gi, 'Hapus'],
    [/\bRemove\b/gi, 'Hapus'],
    [/\bAdd\b/gi, 'Tambah'],
    [/\bSave\b/gi, 'Simpan'],
    [/\bCancel\b/gi, 'Batal'],
    [/\bClose\b/gi, 'Tutup'],
    [/\bOpen\b/gi, 'Buka'],
    [/\bBack\b/gi, 'Kembali'],
    [/\bRetry\b/gi, 'Coba lagi'],
    [/\bLoading\b/gi, 'Memuat'],
    [/\bProcessing\b/gi, 'Memproses'],
    [/\bFailed\b/gi, 'Gagal'],
    [/\bError\b/gi, 'Kesalahan'],
    [/\bWarning\b/gi, 'Peringatan'],
    [/\bSelect\b/gi, 'Pilih'],
    [/\bDirectory\b/gi, 'Folder'],
    [/\bFolder\b/gi, 'Folder'],
    [/\bFile\b/gi, 'File'],
    [/\bModel\b/gi, 'Model'],
    [/\bProvider\b/gi, 'Penyedia'],
    [/\bReasoning\b/gi, 'Penalaran'],
    [/\bLanguage\b/gi, 'Bahasa'],
    [/\bHistory\b/gi, 'Riwayat'],
    [/\bWindow\b/gi, 'Jendela'],
  ];
  for (const [pattern, replacement] of replacements) out = out.replace(pattern, replacement);
  return out;
}

function containsObviousEnglishSentence(text: string): boolean {
  return /\b(the|this|that|with|from|for|and|or|your|you|is|are|was|were|to|of|in|on|when|while|cannot|could|should|please)\b/i.test(text);
}

function looksIndonesian(text: string): boolean {
  return /\b(yang|dan|atau|untuk|dengan|dari|ke|di|pada|ini|itu|sudah|belum|bisa|dapat|pilih|hapus|simpan|buka|tutup|masukkan|gunakan|pengaturan|model|proyek|folder|media|klip|trek|linimasa|bahasa|koneksi|coba|gagal|berhasil|sedang|setelah|sebelum|hingga|pisahkan|koma|utama|opsional|bawaan)\b/i.test(text);
}

export function indonesianUiText(input: unknown, original?: unknown): string {
  const rawOriginal = typeof original === 'string' ? original.trim() : '';
  if (rawOriginal && DIRECT[rawOriginal]) return DIRECT[rawOriginal]!;

  const raw = typeof input === 'string' ? input.trim() : '';
  if (!raw) return '';
  if (DIRECT[raw]) return DIRECT[raw]!;
  if (TECHNICAL_EXACT.has(raw)) return raw;
  if (URL_OR_PATH.test(raw)) return raw;
  if (!/[A-Za-z\u3400-\u9FFF\uF900-\uFAFF]/.test(raw)) return raw;
  if (!HAS_CJK.test(raw) && looksIndonesian(raw)) return raw;

  if (HAS_CJK.test(raw)) return 'Teks antarmuka belum diterjemahkan';

  const converted = replaceCommonEnglish(raw);
  if (converted !== raw && !containsObviousEnglishSentence(converted)) return converted;

  // Short model IDs / format names are technical identifiers, not UI prose.
  if (MODELISH.test(raw) && (/[0-9_.:/@-]/.test(raw) || raw.length <= 5)) return raw;

  // Never leak an untranslated foreign-language sentence into the MiniCut UI.
  return 'Teks antarmuka belum diterjemahkan';
}

export function containsCjk(input: unknown): boolean {
  return typeof input === 'string' && HAS_CJK.test(input);
}
